//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreTerminalCommands.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoreTerminalCommands.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BigDoor 的本地化字符串。
        /// </summary>
        internal static string BigDoor_Clone_ {
            get {
                return ResourceManager.GetString("BigDoor(Clone)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooldown 的本地化字符串。
        /// </summary>
        internal static string Cooldown {
            get {
                return ResourceManager.GetString("Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Death 的本地化字符串。
        /// </summary>
        internal static string death {
            get {
                return ResourceManager.GetString("death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enemies 的本地化字符串。
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Life first, profit quota second 的本地化字符串。
        /// </summary>
        internal static string enemy_tip1 {
            get {
                return ResourceManager.GetString("enemy_tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now very safe, explore as soon as possible 的本地化字符串。
        /// </summary>
        internal static string enemy_tip2 {
            get {
                return ResourceManager.GetString("enemy_tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 inShip 的本地化字符串。
        /// </summary>
        internal static string inShip {
            get {
                return ResourceManager.GetString("inShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverse  的本地化字符串。
        /// </summary>
        internal static string Inverse {
            get {
                return ResourceManager.GetString("Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landmine 的本地化字符串。
        /// </summary>
        internal static string Landmine {
            get {
                return ResourceManager.GetString("Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now Languge 的本地化字符串。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Players 的本地化字符串。
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sec 的本地化字符串。
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipDoor 的本地化字符串。
        /// </summary>
        internal static string ShipDoor {
            get {
                return ResourceManager.GetString("ShipDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipLight 的本地化字符串。
        /// </summary>
        internal static string ShipLight {
            get {
                return ResourceManager.GetString("ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loot In Ship Value 的本地化字符串。
        /// </summary>
        internal static string ShipLoot {
            get {
                return ResourceManager.GetString("ShipLoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch the radar camera view to colleagues who are working. 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teleport 的本地化字符串。
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teleporter 的本地化字符串。
        /// </summary>
        internal static string Teleporter {
            get {
                return ResourceManager.GetString("Teleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turret 的本地化字符串。
        /// </summary>
        internal static string TurretScript {
            get {
                return ResourceManager.GetString("TurretScript", resourceCulture);
            }
        }
    }
}
