//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreTerminalCommands.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoreTerminalCommands.Lang.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 机械门 的本地化字符串。
        /// </summary>
        internal static string BigDoor_Clone_ {
            get {
                return ResourceManager.GetString("BigDoor(Clone)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷却时间 的本地化字符串。
        /// </summary>
        internal static string Cooldown {
            get {
                return ResourceManager.GetString("Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌人列表 的本地化字符串。
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狒狒鹰   的本地化字符串。
        /// </summary>
        internal static string enemy_Baboon_hawk {
            get {
                return ResourceManager.GetString("enemy_Baboon hawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 史莱姆   的本地化字符串。
        /// </summary>
        internal static string enemy_Blob {
            get {
                return ResourceManager.GetString("enemy_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地堡蜘蛛   的本地化字符串。
        /// </summary>
        internal static string enemy_Bunker_Spider {
            get {
                return ResourceManager.GetString("enemy_Bunker Spider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱脸虫   的本地化字符串。
        /// </summary>
        internal static string enemy_Centipede {
            get {
                return ResourceManager.GetString("enemy_Centipede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半身鱼   的本地化字符串。
        /// </summary>
        internal static string enemy_Crawler {
            get {
                return ResourceManager.GetString("enemy_Crawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑影   的本地化字符串。
        /// </summary>
        internal static string enemy_Flowerman {
            get {
                return ResourceManager.GetString("enemy_Flowerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巨人   的本地化字符串。
        /// </summary>
        internal static string enemy_ForestGiant {
            get {
                return ResourceManager.GetString("enemy_ForestGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 囤积虫   的本地化字符串。
        /// </summary>
        internal static string enemy_Hoarding_bug {
            get {
                return ResourceManager.GetString("enemy_Hoarding bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐盒小丑   的本地化字符串。
        /// </summary>
        internal static string enemy_Jester {
            get {
                return ResourceManager.GetString("enemy_Jester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸟   的本地化字符串。
        /// </summary>
        internal static string enemy_Manticoil {
            get {
                return ResourceManager.GetString("enemy_Manticoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假人   的本地化字符串。
        /// </summary>
        internal static string enemy_Masked {
            get {
                return ResourceManager.GetString("enemy_Masked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无眼狗 的本地化字符串。
        /// </summary>
        internal static string enemy_MouthDog {
            get {
                return ResourceManager.GetString("enemy_MouthDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃夹子   的本地化字符串。
        /// </summary>
        internal static string enemy_Nutcracker {
            get {
                return ResourceManager.GetString("enemy_Nutcracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孢子蜥蜴   的本地化字符串。
        /// </summary>
        internal static string enemy_Puffer {
            get {
                return ResourceManager.GetString("enemy_Puffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静电蜜蜂   的本地化字符串。
        /// </summary>
        internal static string enemy_Red_Locust_Bees {
            get {
                return ResourceManager.GetString("enemy_Red Locust Bees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹簧头   的本地化字符串。
        /// </summary>
        internal static string enemy_Spring {
            get {
                return ResourceManager.GetString("enemy_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命第一，指标第二 的本地化字符串。
        /// </summary>
        internal static string enemy_tip1 {
            get {
                return ResourceManager.GetString("enemy_tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设施里面没有敌人，尽快探索吧！ 的本地化字符串。
        /// </summary>
        internal static string enemy_tip2 {
            get {
                return ResourceManager.GetString("enemy_tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反向 的本地化字符串。
        /// </summary>
        internal static string Inverse {
            get {
                return ResourceManager.GetString("Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string Landmine {
            get {
                return ResourceManager.GetString("Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前语言： 的本地化字符串。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船舱门 的本地化字符串。
        /// </summary>
        internal static string ShipDoor {
            get {
                return ResourceManager.GetString("ShipDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船灯 的本地化字符串。
        /// </summary>
        internal static string ShipLight {
            get {
                return ResourceManager.GetString("ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前飞船物品价值 的本地化字符串。
        /// </summary>
        internal static string ShipLoot {
            get {
                return ResourceManager.GetString("ShipLoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送中 的本地化字符串。
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送器 的本地化字符串。
        /// </summary>
        internal static string Teleporter {
            get {
                return ResourceManager.GetString("Teleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机枪 的本地化字符串。
        /// </summary>
        internal static string TurretScript {
            get {
                return ResourceManager.GetString("TurretScript", resourceCulture);
            }
        }
    }
}
